CREATE TABLE produit (
  ID_PRODUIT SERIAL PRIMARY KEY,
  MARQUE VARCHAR(100),
  MODELE VARCHAR(100),
  PRIX int
);

CREATE TABLE CLIENT (
  ID_CLIENT SERIAL PRIMARY KEY,
  NOM VARCHAR(30),
  PRENOM VARCHAR(30),
  CIVILITE VARCHAR(30),
  ADRESSE VARCHAR(200),
  CP VARCHAR(10),
  VILLE VARCHAR(100),
  PAYS varchar(100),
  telephone varchar(20),  
  LOGIN VARCHAR(30),
  PASSWORD VARCHAR(256) 
);